### ISSUE TITLE
Indication of an applied change

### ISSUE THREAD

**Issue by amchiclet** [reprogrammer/cascade#2]
After the user applies a change, the error list should be updated. Also there should be a UI indication that the change has been applied, e.g. graying out the text.

Currently, there's no way to determine from the UI which change has already been applied.

**Comment by reprogrammer** [comment]
A high level implementation question: I can think of at least two ways to keep track of the disabled nodes. First, keep a collection of disabled nodes as the current implementation does. Second, add a flag to the `TreeObject` class, which would say whether the tree node is enabled or disabled. I don't have any preferences. I'm simply interested in knowing how you made this design decision.

**Comment by reprogrammer** [comment]
The next step is to reenable the tree nodes corresponding to a change after the user undoes a change.
