### ISSUE TITLE
Show metrics on a change

### ISSUE THREAD

**Issue by amchiclet** [reprogrammer/cascade#21]
It would be useful if we had metrics that would help users decide which tree to explore. Some ideas are the following.
1. Show how many immediate errors a change removes
2. Show how many eventual errors a change introduces
3. Show how many changes follow a certain change
4. Show how many immediate errors a change introduces
5. Show how many intermediate errors a change introduces

A good direction would be to start on the (1)-(3).

(1) should be indicated on the label of the change node. (2) and (3) should be indicated as a tool tip.

**Comment by reprogrammer** [comment]
I'm going to close this issue for now. If we decide to add more information to the summary, we'll open a new issue.
