### ISSUE TITLE
Inserted annotations include new lines

### ISSUE THREAD

**Issue by amchiclet** [reprogrammer/cascade#27]
Annotating a type should not insert an unnecessary new line. It makes the code looks ugly.

**Comment by reprogrammer** [comment]
I confirmed that updating Eclipse fixes this issue. I simply installed the latest version of [Eclipse with Java 8 support](http://www.eclipse.org/downloads/packages/eclipse-rcp-and-rap-developers/keplersr2-with-java8-patches) and used it as the running Eclipse. We no longer need the source codes of Eclipse LTK and JDT plug-ins in the workspace. I updated the wiki page for [setting up the development environment](https://github.com/reprogrammer/universal-type-qualifier-inference/wiki/Setting-Up-the-Development-Environment).
