### ISSUE TITLE
Make the status of expansion icons stable

### ISSUE THREAD

**Issue by reprogrammer** [reprogrammer/cascade#33]
Let's say the expansion icon of an error `e` is `|>`. Let's assume that if the user expands `e`, the expansion icon will disappear because there is no resolution associated with `e`. Later, if the user selects a different node of the tree such that `e` is no longer in the focus, the expansion icon of `e` should not go back to `|>`.

**Comment by amchiclet** [comment]
Fixed by b27caab84935a00b97a909c6a97c4ca8b476181c.
