### ISSUE TITLE
Change is disabled but the error that it resolves is enabled

### ISSUE THREAD

**Issue by reprogrammer** [reprogrammer/cascade#61]
I started applying the changes proposed for the jolden project from the top of the tree.

`Change field bodyTab to @Nullable Body` is marked as applied but its parent error `bodyTab = null` is not marked as resolved.

Similarly, `Change field next to @Nullable Body` is marked as fixed while its corresponding error `next = null` is not marked as resolved.

![change-disabled-error-enabled](https://cloud.githubusercontent.com/assets/153710/2813249/e39bd02a-ce81-11e3-80e4-b05540335e56.png)

**Comment by amchiclet** [comment]
Duplicate with #51.
